#!/usr/bin/env bash

if [ "$#" -lt 2 ]; then
    echo "Usage: push <file_name> <commit_message>"
    exit 1
fi

file_name=$1
commit_message=$2

if test -f $file_name; then
    git add $file_name
    git commit -m "$commit_message"
    git push
else
    echo "File <$file_name> not found"
fi

